//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Bd_GYMEntities : DbContext
    {
        public Bd_GYMEntities()
            : base("name=Bd_GYMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admins> Admins { get; set; }
        public DbSet<C_congeladas> C_congeladas { get; set; }
        public DbSet<Caja> Caja { get; set; }
        public DbSet<Clientes> Clientes { get; set; }
        public DbSet<Creditos> Creditos { get; set; }
        public DbSet<Dptos> Dptos { get; set; }
        public DbSet<Empresas> Empresas { get; set; }
        public DbSet<Estados_fact> Estados_fact { get; set; }
        public DbSet<Estados_pers> Estados_pers { get; set; }
        public DbSet<Facturas> Facturas { get; set; }
        public DbSet<Municipios> Municipios { get; set; }
        public DbSet<Paises> Paises { get; set; }
        public DbSet<Personas> Personas { get; set; }
        public DbSet<Planes> Planes { get; set; }
        public DbSet<Sedes> Sedes { get; set; }
        public DbSet<Servicios> Servicios { get; set; }
        public DbSet<Servs_Plns> Servs_Plns { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<T_estados> T_estados { get; set; }
        public DbSet<Tipos_pgs> Tipos_pgs { get; set; }
    }
}
